# netlify.toml
[build]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions"

# Define function paths
[functions]
  directory = "functions"  # Where your serverless functions live

# Optional: Add environment variables (set in Netlify UI)
# [context.production]
#   environment = { NODE_ENV = "production" }
[build.environment]
  NODE_VERSION = "20"

# Optional: Custom redirects (for SPA routing)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
