# netlify.toml
[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  build_directory = "functions-build"  # ← This is the fix!

# Optional: Set Node.js version (recommended)
[build.environment]
  NODE_VERSION = "18"

# Optional: Set deploy context (e.g., for PR previews)
[context.production]
  publish = "."
  functions = "netlify/functions"

[context.develop]
  publish = "."
  functions = "netlify/functions"
