# netlify.toml
[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

# Optional: Set Node.js version (recommended)
[build.environment]
  NODE_VERSION = "18"

# Optional: Set deploy context (e.g., for PR previews)
[context.production]
  publish = "."
  functions = "netlify/functions"

[context.develop]
  publish = "."
  functions = "netlify/functions"
