# netlify.toml
[build]
  command = "next build"
  publish = ".next"
  # Optional: Set the directory for static files
  # publish = ".next/public"

# Define serverless functions
[[plugins]]
  package = "@netlify/plugin-functions"

# Define function paths
[functions]
  directory = "functions"  # Where your serverless functions live

# Optional: Add environment variables (set in Netlify UI)
# [context.production]
#   environment = { NODE_ENV = "production" }

# Optional: Custom redirects (for SPA routing)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
